name: proyecto_padawan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  firebase_auth: ^6.1.1
  flutter_localization: ^0.3.3
  get: ^4.7.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  custom_paint: ^0.0.1
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  workmanager: ^0.9.0+3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
       - assets/images/
