// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcC7yLEuQMgIY2N47swwRS_eDSbuKYjaE',
    appId: '1:691694758561:web:9469e144559c3891019ee0',
    messagingSenderId: '691694758561',
    projectId: 'projectpadawan',
    authDomain: 'projectpadawan.firebaseapp.com',
    storageBucket: 'projectpadawan.firebasestorage.app',
    measurementId: 'G-NNG89PDCF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5pp0uDN4ynUU07r3Q0MRX_-0la0jr2JE',
    appId: '1:691694758561:android:ab9afc28b67e9db4019ee0',
    messagingSenderId: '691694758561',
    projectId: 'projectpadawan',
    storageBucket: 'projectpadawan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASehbWQKwbfQZ5vDDLzcBSIVSc8zvPbSQ',
    appId: '1:691694758561:ios:27d7a0f3a28dcb12019ee0',
    messagingSenderId: '691694758561',
    projectId: 'projectpadawan',
    storageBucket: 'projectpadawan.firebasestorage.app',
    iosBundleId: 'com.example.proyectoPadawan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASehbWQKwbfQZ5vDDLzcBSIVSc8zvPbSQ',
    appId: '1:691694758561:ios:27d7a0f3a28dcb12019ee0',
    messagingSenderId: '691694758561',
    projectId: 'projectpadawan',
    storageBucket: 'projectpadawan.firebasestorage.app',
    iosBundleId: 'com.example.proyectoPadawan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcC7yLEuQMgIY2N47swwRS_eDSbuKYjaE',
    appId: '1:691694758561:web:a7ee229ec2f14de3019ee0',
    messagingSenderId: '691694758561',
    projectId: 'projectpadawan',
    authDomain: 'projectpadawan.firebaseapp.com',
    storageBucket: 'projectpadawan.firebasestorage.app',
    measurementId: 'G-15X2GSHS6W',
  );
}
