// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARZ3L0YOqFIVtvAdtR89pFHbXECmgjY7Q',
    appId: '1:64593160087:web:0051674fe8f37b42e4c6d2',
    messagingSenderId: '64593160087',
    projectId: 'login-1ea92',
    authDomain: 'login-1ea92.firebaseapp.com',
    storageBucket: 'login-1ea92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfSh8V7zxhoUy_tyXunLLc6M2aCrnjWgY',
    appId: '1:64593160087:android:d89ac2be3a93765de4c6d2',
    messagingSenderId: '64593160087',
    projectId: 'login-1ea92',
    storageBucket: 'login-1ea92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzH2oSmgfOSA8S-nTqF8x9PpyCR7m-lk',
    appId: '1:64593160087:ios:1065a8b4553ca62ae4c6d2',
    messagingSenderId: '64593160087',
    projectId: 'login-1ea92',
    storageBucket: 'login-1ea92.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKzH2oSmgfOSA8S-nTqF8x9PpyCR7m-lk',
    appId: '1:64593160087:ios:1065a8b4553ca62ae4c6d2',
    messagingSenderId: '64593160087',
    projectId: 'login-1ea92',
    storageBucket: 'login-1ea92.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARZ3L0YOqFIVtvAdtR89pFHbXECmgjY7Q',
    appId: '1:64593160087:web:b8ad7cf5f94e1666e4c6d2',
    messagingSenderId: '64593160087',
    projectId: 'login-1ea92',
    authDomain: 'login-1ea92.firebaseapp.com',
    storageBucket: 'login-1ea92.firebasestorage.app',
  );
}
