// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWqASwnvHA8znAKRuZRyC9SdsWAnjLWF4',
    appId: '1:479406867363:web:aca5cbb0210ed3737dd016',
    messagingSenderId: '479406867363',
    projectId: 'loginfirebase-4e722',
    authDomain: 'loginfirebase-4e722.firebaseapp.com',
    storageBucket: 'loginfirebase-4e722.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANdaIrBJcyllW6_v330ghR3-SDrqwqMc',
    appId: '1:479406867363:android:b9d6152534de05217dd016',
    messagingSenderId: '479406867363',
    projectId: 'loginfirebase-4e722',
    storageBucket: 'loginfirebase-4e722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30tIDQlqeMHCMPP85bx_mgmBb28IDjqA',
    appId: '1:479406867363:ios:f75e44727eb390247dd016',
    messagingSenderId: '479406867363',
    projectId: 'loginfirebase-4e722',
    storageBucket: 'loginfirebase-4e722.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30tIDQlqeMHCMPP85bx_mgmBb28IDjqA',
    appId: '1:479406867363:ios:f75e44727eb390247dd016',
    messagingSenderId: '479406867363',
    projectId: 'loginfirebase-4e722',
    storageBucket: 'loginfirebase-4e722.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWqASwnvHA8znAKRuZRyC9SdsWAnjLWF4',
    appId: '1:479406867363:web:8dadaf7b1ca473097dd016',
    messagingSenderId: '479406867363',
    projectId: 'loginfirebase-4e722',
    authDomain: 'loginfirebase-4e722.firebaseapp.com',
    storageBucket: 'loginfirebase-4e722.firebasestorage.app',
  );
}
